export { default as Homepage } from "./Homepage";
export { default as Navbar } from "./Navbar";
// export { default as News } from "./News";
export { default as Cryptocurrencies } from "./Cryptocurrencies";
// export { default as Exchanges } from "./Exchanges";
export { default as CryptoDetails } from "./CryptoDetails";
export { default as Newpage } from "./Newpage";
export { default as Home } from "./Home";
export { default as Currency } from "./Currency";
export { default as Footer } from "./Footer";
export { default as Forex } from "./Forex";
export { default as ForexHome } from "./ForexHome";
export { default as CoinBox1 } from "./CoinBox1";
export { default as CoinPage } from "./CoinPage";
export { default as Search } from "./Search";
